---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.exporter.name }}
spec:
  selector:
    app: {{ $.Values.exporter.name }}
  clusterIP: None
  ports:
  - protocol: TCP
    port: {{ $.Values.exporter.listening_port | quote }}
    targetPort: {{ $.Values.exporter.listening_port | quote }}
    name: metric_collection
